`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 09.01.2025 11:36:15
// Design Name: 
// Module Name: one_bit_carry_select_adder
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module one_bit_carry_select_adder(inn1,inn2,carry_in,sum,carry_out);
    input inn1,inn2,carry_in;
    output sum,carry_out;
    wire internal_sum1,internal_sum2,internal_carry1,internal_carry2;  //for internal sum & carry generated by full adder module
    fuller_adder full_adder_1(inn1,inn2,1'b0,internal_sum1,internal_carry1); //imported full adder module & connect it
    fuller_adder full_adder_2(inn1,inn2,1'b1,internal_sum2,internal_carry2);//imported full adder module & connect it
    two_one_mux mux1(internal_carry1,internal_carry2,carry_in,carry_out);//imported mux module & connect it
    two_one_mux mux2(internal_sum1,internal_sum2,carry_in,sum);//imported mux module & connect it
    
endmodule
