`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 03.02.2025 00:30:53
// Design Name: 
// Module Name: adder_carry_select
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
module full_adder(inn1,inn2,carry_in,sum,carry_out);
    input inn1,inn2,carry_in;    //taken 2 input & carry_in wire for fulladder input
    output sum,carry_out; //taken output of sum,carry 
    
    assign sum=inn1^inn2^carry_in; //use concatenation operator for sum& carry_out generation
    assign carry_out=(inn1 & inn2)|(inn2 & carry_in)|(inn1 & carry_in);
endmodule

module one_bit_carry_select_adder(inn1,inn2,carry_in,sum,carry_out);
    input inn1,inn2,carry_in;
    output sum,carry_out;
    wire internal_sum1,internal_sum2,internal_carry1,internal_carry2;  //for internal sum & carry generated by full adder module
    
    full_adder full_adder_1(inn1,inn2,1'b0,internal_sum1,internal_carry1); //imported full adder module & connect it
    full_adder full_adder_2(inn1,inn2,1'b1,internal_sum2,internal_carry2);//imported full adder module & connect it
    
    two_one_mux mux1(internal_carry1,internal_carry2,carry_in,carry_out);//imported mux module & connect it
    two_one_mux mux2(internal_sum1,internal_sum2,carry_in,sum);//imported mux module & connect it
    
endmodule

module two_one_mux(inn1,inn2,sel,out);
    input inn1,inn2,sel; //input for mux & select line
    output out; //output for mux
    assign out=sel?inn2:inn1; //use terninary operator for mux operation
endmodule

module n_bit_carry_select_adder(innA,innB,control,sum);
    parameter   number_of_adder=32;
    input [number_of_adder-1:0] innA,innB;
    input control;
    output[number_of_adder-1:0] sum;
    
    wire [number_of_adder-1:0] xor_inn2;
    wire[number_of_adder:0] int_carry;  //internal_carry function
    
    assign int_carry[0]=control;
    
    

    genvar i;


    generate    for(i=0;i<number_of_adder;i=i+1)
        begin: byte_adder //name of block
            //initialization of 32 1B carry select Adder using generate
            assign xor_inn2[i]=innB[i]^control;     //2'S complement block
            one_bit_carry_select_adder add(innA[i],xor_inn2[i],int_carry[i],sum[i],int_carry[i+1]); //import 1 bit carry
            
        end
    
    endgenerate     

endmodule
